# Generated by Django 4.2.10 on 2024-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('testimonial', models.TextField()),
                ('rating', models.IntegerField(choices=[(0, '0 STAR'), (1, '1 STAR'), (2, 'STARS'), (3, 'STARS'), (4, 'STARS'), (5, '5 STARS')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Published'), (1, 'Published')], default=0)),
            ],
        ),
    ]
