# Generated by Django 4.2.10 on 2024-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(0, '0 STAR'), (1, '1 STAR'), (2, '2 STARS'), (3, '3 STARS'), (4, '4 STARS'), (5, '5 STARS')], default=0),
        ),
    ]
