# Generated by Django 4.2.10 on 2024-02-19 22:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_options_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
