# Generated by Django 4.2.10 on 2024-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(0, 'General'), (2, 'Technology'), (3, 'Business'), (4, 'Science')], default=0),
        ),
    ]
